### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by nassssmgk** [LunyaticCat/ProjetHTMLCours#2]
_**<!DOCTYPE html>_
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="css/styles.css">
		<meta charset="utf-8">

   		<title>Le site non officiel de Chuck Norris</title>**

**Comment by LunyaticCat** [comment]
yup, ça fonctionne bien.

**Comment by LunyaticCat** [comment]
wait, non pas du tout

**Comment by LunyaticCat** [comment]
tu est dans "Issues" là, c'est l'endroit ou les gens rapporte les problème. Tu est censé me faire parvenir tes modifications par pull requests.
